name: Deploy Application
on:
  push:
    branches: main
    paths:
      - '**.ts'
      - 'package*.json'
      - '.env'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps and build
        run: |
          npm ci
          npm run build

      - name: Set .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENVIRONMENT: prod
          envkey_PORT: ${{ secrets.PORT }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
          directory: dist
          file_name: .env
          fail_on_empty: true

      - name: Remove previous deployment and stop process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            npx pm2 stop auth-service
            npx pm2 delete auth-service
            rm -rf /var/www/auth-service
            mkdir /var/www/auth-service

      - name: ls
        run: ls

      - name: Transfer application to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: dist
          target: /var/www/auth-service

      - name: Transfer dependencies to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: node_modules
          target: /var/www/auth-service

      - name: Deploy and start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/auth-service/dist
            npx pm2 start --name auth-service main.js